# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeECC <- function(D, maxhomDim, scaleSeq) {
    .Call(`_TDAvec_computeECC`, D, maxhomDim, scaleSeq)
}

computePES <- function(D, homDim, scaleSeq) {
    .Call(`_TDAvec_computePES`, D, homDim, scaleSeq)
}

computePI <- function(D, homDim, xSeq, ySeq, res, sigma) {
    .Call(`_TDAvec_computePI`, D, homDim, xSeq, ySeq, res, sigma)
}

computePL <- function(D, homDim, scaleSeq, k) {
    .Call(`_TDAvec_computePL`, D, homDim, scaleSeq, k)
}

computePS <- function(D, homDim, scaleSeq, p) {
    .Call(`_TDAvec_computePS`, D, homDim, scaleSeq, p)
}

computeVAB <- function(D, homDim, scaleSeq) {
    .Call(`_TDAvec_computeVAB`, D, homDim, scaleSeq)
}

computeVPB <- function(D, homDim, xSeq, ySeq, tau) {
    .Call(`_TDAvec_computeVPB`, D, homDim, xSeq, ySeq, tau)
}

